#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'qt4gui',
 'build_date': '2012-08-20 14:37:30 +0200',
 'clean': None,
 'date': '2012-07-30 16:40:26 +0200',
 'revision_id': 'knaup-20120730144026-68imrrh90jxy3yzu',
 'revno': 147}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
