# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'periodicExpand.ui'
#
# Created: Thu Aug 23 17:57:57 2012
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_periodicExpand(object):
    def setupUi(self, periodicExpand):
        periodicExpand.setObjectName("periodicExpand")
        periodicExpand.resize(218, 197)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(periodicExpand.sizePolicy().hasHeightForWidth())
        periodicExpand.setSizePolicy(sizePolicy)
        periodicExpand.setMinimumSize(QtCore.QSize(0, 0))
        periodicExpand.setMaximumSize(QtCore.QSize(65536, 65536))
        periodicExpand.setBaseSize(QtCore.QSize(300, 310))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/GSLogoPeriodic.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        periodicExpand.setWindowIcon(icon)
        self.widget = QtGui.QWidget(periodicExpand)
        self.widget.setGeometry(QtCore.QRect(0, 0, 217, 196))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.aSpinBox = QtGui.QSpinBox(self.widget)
        self.aSpinBox.setMinimum(1)
        self.aSpinBox.setObjectName("aSpinBox")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.aSpinBox)
        self.bSpinBox = QtGui.QSpinBox(self.widget)
        self.bSpinBox.setMinimum(1)
        self.bSpinBox.setObjectName("bSpinBox")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.bSpinBox)
        self.cSpinBox = QtGui.QSpinBox(self.widget)
        self.cSpinBox.setMinimum(1)
        self.cSpinBox.setObjectName("cSpinBox")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.cSpinBox)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_4)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.okButton = QtGui.QPushButton(self.widget)
        self.okButton.setAutoDefault(False)
        self.okButton.setDefault(False)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtGui.QPushButton(self.widget)
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setDefault(True)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(periodicExpand)
        QtCore.QObject.connect(self.okButton, QtCore.SIGNAL("clicked()"), periodicExpand.accept)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL("clicked()"), periodicExpand.reject)
        QtCore.QMetaObject.connectSlotsByName(periodicExpand)
        periodicExpand.setTabOrder(self.cancelButton, self.okButton)

    def retranslateUi(self, periodicExpand):
        periodicExpand.setWindowTitle(QtGui.QApplication.translate("periodicExpand", "Periodic Repetition", None, QtGui.QApplication.UnicodeUTF8))
        periodicExpand.setToolTip(QtGui.QApplication.translate("periodicExpand", "Geometry periodic expansion dialog", None, QtGui.QApplication.UnicodeUTF8))
        periodicExpand.setWhatsThis(QtGui.QApplication.translate("periodicExpand", "This Dialog allows to periodically expand supercell geometries", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("periodicExpand", "Periodic Expansion", None, QtGui.QApplication.UnicodeUTF8))
        self.aSpinBox.setToolTip(QtGui.QApplication.translate("periodicExpand", "number of old cells in a direction", None, QtGui.QApplication.UnicodeUTF8))
        self.bSpinBox.setToolTip(QtGui.QApplication.translate("periodicExpand", "number of old cells in c direction", None, QtGui.QApplication.UnicodeUTF8))
        self.cSpinBox.setToolTip(QtGui.QApplication.translate("periodicExpand", "number of old cells in c direction", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("periodicExpand", "a direction", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("periodicExpand", "b direction", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("periodicExpand", "c direction", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("periodicExpand", "Number of Unit Cells", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setToolTip(QtGui.QApplication.translate("periodicExpand", "expand supercell and leave dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("periodicExpand", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setToolTip(QtGui.QApplication.translate("periodicExpand", "cancel periodic expansion", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("periodicExpand", "cancel", None, QtGui.QApplication.UnicodeUTF8))

import gsresources_rc
