#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'trunk',
 'build_date': '2012-07-27 17:37:14 +0200',
 'clean': None,
 'date': '2012-07-27 17:37:01 +0200',
 'revision_id': 'janknaup@gmail.com-20120727153701-ldjjutw0ma5qao61',
 'revno': 146}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
