#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'trunk',
 'build_date': '2012-09-27 15:00:23 +0200',
 'clean': None,
 'date': '2012-09-27 14:53:58 +0200',
 'revision_id': 'janknaup@gmail.com-20120927125358-z7wpck0evgnuxemk',
 'revno': 152}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
