#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'trunk',
 'build_date': '2012-07-06 11:57:36 +0200',
 'clean': None,
 'date': '2012-07-06 11:48:21 +0200',
 'revision_id': 'janknaup@gmail.com-20120706094821-6r1x7uoxi2wqgko0',
 'revno': 135}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
