#!/usr/bin/python
##############################################################################
# pesto
# Part of COmputational MAterials SCIence toolkit - comatsci
# (c) 2005-2008 by Jan M. Knaup <janknaup@gmail.com>
# all rights reserved
##############################################################################
# Licensed under the Non-Profit Open Software License version 3.0
# see file LICENSE for details.
##############################################################################

import time,signal,random

import os,sys

versionname="python%d.%d" % sys.version_info[0:2]

sys.path.append(os.path.join(os.path.dirname(sys.argv[0]),
		"../lib/",versionname,"site-packages"))

import comatsci,comatsci.dimer

from optparse import OptionParser

import ConfigParser

# Catch SIGINT and SIGXCPU to gracefully shut down

stopsignal=None
startdir=os.path.realpath(".")

def stophandler(signum, frame):
	"""Catch Signals at which we want to stop gracefully, but abort semi hard, if signal is encountered again"""
	global stopsignal
	global startpath
	if stopsignal==None:
		if signum==signal.SIGINT:
			stopsignal="SIGINT"
		elif signum==signal.SIGXCPU:
			stopsignal="SIGXCPU"
		else:
			stopsignal=="UNKNOWN"
		print "Signal %s encountered, will stop after next translation step" %(stopsignal)
		curdir=os.path.realpath(".")
		os.chdir(startpath)
		sf=open("STOP_PESTO","w")
		sf.write(stopsignal)
		sf.close()
		os.chdir(curdir)
	else:
		print "Okay, Okay, will shutdown right now."
		sys.exit(signum)



def calcinitializer(options):
	"""initialize calculator"""
	#initialize calculator
	if options.calculator=="dftb":
		calc=comatsci.calculators.dftbcalc(optionfname="pypath.ini",verbosity=options.verbosity)
	elif options.calculator=="siesta":
		calc=comatsci.calculators.siestacalc(optionfname="pypath.ini",verbosity=options.verbosity)
	elif options.calculator=="noodle":
		calc=comatsci.calculators.noodlecalc(optionfname="pypath.ini",verbosity=options.verbosity)
	elif options.calculator=="gaussian":
		calc=comatsci.calculators.gaussiancalc(optionfname="pypath.ini",verbosity=options.verbosity)
	elif options.calculator=="muellerbrown":
		calc=comatsci.calculators.muellerBrownCalc(verbosity=options.verbosity)
	else:
		raise Exception("unknown calculator")
	return calc


def dimerrun(mode):
	options, config, args = readconfig_options(mode="s")

	# Be Yakky
	
	SCHEDNAMES={
		's'	:	"serial",
		'p' : "MPI",
	}
	
	if options.verbosity >= comatsci.constants.VBL_NORMAL:
		print """
                    **************************
                    *** pesto %10s ***
                    **************************
    (c) Jan M. Knaup <janknaup@gmail.com>
    Licensed under the Non-Profit Open Software License version 3.0
    see attached LICENSE file for details

    PortablE State of Transition Optimizer
    (using the improved Dimer Method, cf. J. Chem. Phys. 123, 224101 (2005))

using the following options:
     calculator             : %s
     scheduler              : %s
     maximim interations    : %d
     force tol.             : %e
     rms force tol.         : %e
     system charge          : %e
     hard trial translation : %e
     rotation skip angle    : %e\n\n""" % (comatsci.constants.VERSION,options.calculator,
			SCHEDNAMES[options.scheduler],options.maxit,options.forcetol,
		options.rmstol,options.charge,options.hardtranslation,options.rotskipangle)
	
	if options.fixedatoms!="":
		tmp=options.fixedatoms.split(',')
		# user fixed atom indices start at 1, internal format counts from 0
		fixatms=[ int(s)-1 for s in tmp ]
		if options.verbosity >= comatsci.constants.VBL_NORMAL:
			print "The following atoms will be kept fixed:"
			print fixatms
	else:
		if options.verbosity >= comatsci.constants.VBL_NORMAL:
			print " *** WARNING: No atoms will be kept fixed. This is usually a bad idea"
		fixatms=[]
	
	# initialize scheduler and calculator
	if options.scheduler.lower()=="s":
		scheduler=comatsci.schedulers.serialScheduler(calcinitializer(options), options.verbosity)
		if options.verbosity >= comatsci.constants.VBL_NORMAL:
			print "initialized serial scheduler"
	elif options.scheduler.lower()=="p":
		scheduler=comatsci.schedulers.mpiScheduler(calcinitializer,options, options.verbosity)
		if options.verbosity >= comatsci.constants.VBL_NORMAL:
			print "initialized parallel scheduler."
	elif options.scheduler.lower()=="t":
		scheduler=comatsci.schedulers.threadScheduler(calcinitializer, options, options.maxthreads, options.verbosity)
		if options.verbosity >= comatsci.constants.VBL_NORMAL:
			print "inialized threading schduler with maximum %d concurrent threads" % scheduler.maxWorkThreads
	else:
		raise "unknown scheduler"
	
	# construct dimer options dictionary
	dimeroptions={
	"maxFt":options.forcetol,
	"maxFp":options.forcetol,
	"maxFtRMS":options.rmstol,
	"maxFpRMS":options.rmstol,
	"rotskipangle":options.rotskipangle,
	"hardTranslation":options.hardtranslation,
	"maxIt":options.maxit,
	"fixedAtoms":fixatms,
	}
	
	#initialize dimer
	
	dimer=comatsci.dimer.Dimer(dimeroptions)
	dimer.fixedAtoms=fixatms
	
	# read dimer file
	
	dimer.readfile(args[0])
	dimer.setDisplacement(options.displacement/comatsci.constants.ANGSTROM)
	
	startclock=time.clock()
	startwalltime=time.time()
	
	dimer.dimerIterate(scheduler)
	
	endclock=time.clock()
	endwalltime=time.time()
	
##	print dimer.E0
##	print dimer.f0
##	print "----------------"
##	print dimer.E1
##	print dimer.f1

	

	
	dimer.writefmg("dimer_end.fmg")
	
	if options.verbosity >= comatsci.constants.VBL_NORMAL:
		print "\nFinished after %d dimer iterations and %d total Energy calculations in %d SCF cycles" % (dimer.stepCount,scheduler.jobCount,scheduler.iterationCount)
		print "Script runtime %f seconds CPU, %f seconds wall time" % (endclock-startclock,endwalltime-startwalltime)
		print "Calculator runtime %f seconds CPU, %f seconds wall time\n\n" % (scheduler.cpuTime,scheduler.wallTime)
	if options.verbosity >= comatsci.constants.VBL_NORMAL:
		print "shutting down scheduler and calculator(s)"
	scheduler.shutdown()
	
	#some stuff to do when finished
	ratheryoudidnts=["""1. I'd Really Rather You Didn't Act Like A Sanctimonious, Holier-Than-Thou Ass When 
Describing My Noodly Goodness. If Some People Don't Believe in Me, That's Okay. Really, 
I'm Not That Vain. Besides, This Isn't About Them So Don't Change The Subject.""",
	"""2. I'd Really Rather You Didn't Use My Existence As A Means To Oppress, Subjugate, Punish, 
Eviscerate, And/Or, You Know, Be Mean To Others. I Don't Require Sacrifices And Purity Is 
For Drinking Water, Not People""",
	"""3. I'd Really Rather You Didn't Judge People For The Way They Look, Or How They Dress, 
Or The Way They Talk, Or, Well, Just Play Nice, Okay? 
Oh, And Get This Into Your Thick Heads: Woman=Person. Man=Person. Samey-Samey. One Is Not 
Better Than The Other, Unless We're Talking About Fashion And I'm Sorry, But I Gave That To 
Women And Some Guys Who Know The Difference Between Teal And Fuchsia.""",
	"""4. I'd Really Rather You Didn't Indulge In Conduct That Offends Yourself, Or Your Willing,
Consenting Partner Of Legal Age AND Mental Maturity. As For Anyone Who Might Object, I 
Think The Expression Is Fo F*** Yourself, Unless They Find That Offensive In Which Case 
They Can Turn Off The TV For Once And Go For A Walk For A Change.""",
	"""5. I'd Really Rather You Didn't Challenge The Bigoted, Misogynist, Hateful Ideas Of Others 
On An Empty Stomach. Eat, Them Go After The B*******.""",
	"""6. I'd Really Rather You Didn't Build Multimillion-Dollar Churches/Temples/Mosques/Shrines 
To My Noodly Goodness When The Money Could Be Better Spent (Take Your Pick):
  A. Ending Poverty
  B. Curing Deseases
  C. Living In Peace, Loving With Passion And Lowering The Cost Of Cable
I Might Be A Complex-Carbohydrate Omniscient Being, But I Enjoy The Simple Things In Life. 
I Ought To Know. I AM The Creator.""",
	"""7. I'd Really Rather You Didn't Go Around Telling People I Talk To You. You're Not That
Interesting. Get Over Yourself. And I Told You To Love Your Fellow Man, Can't You Take 
A Hint?""",
	"""8. I'd Really Rather You Didn't Do Unto Other As You Would Have Them Do Unto You If You 
Are Into, Um, Stuff That Uses A Lot Of Lubricant/Leather/Las Vegas. If The Other Is Into 
It, However (Pursuant To #4), Then Have At It, Take Pictures, And For The Love Of Mike, 
Wear A CONDOM! Honestly, It's A Piece Of Rubber. If I Didn't Want It To Feel Good When 
You Did IT I Would Have Added Spikes, Or Something."""]
	
	if options.verbosity >= comatsci.constants.VBL_NORMAL:
		print random.choice(ratheryoudidnts)
		print "\nFrom Bobby Henderson, The Gospel of the Flying Spaghetti Monster, Villard, New York, 2006\n\n"

def readconfig_options(mode="s"):
	# Default values
	configdefaults=dict(
		maxit="100",
		rmstol="1e-5",
		forcetol="1e-4",
		calculator="dftb",
		fixedatoms="",
		relmode='s',
		charge='0.0',
		hardtranslation='0.01',
		rotskipangle='0.01',
		displacement='0.01'
	)
	
	# valid calculator types
	# threading mode put on ice for now, as it requires major changes to all calculators
##	VALIDSCHEDS=['s','p','t']
	VALIDSCHEDS=['s','p']

	# Read pypath.ini

	config = ConfigParser.SafeConfigParser(defaults=configdefaults)
	config.read("pypath.ini")
	if not config.has_section("NEB"):
		config.add_section("NEB")
	if not config.has_section("comatsci"):
		config.add_section("comatsci")
	if not config.has_section("DIMER"):
		config.add_section("DIMER")

	#Parse Options

	usage="usage: %prog [options] <dimer file>\nLicensed under the Non-Profit Open Software License version 3.0"

	parser=OptionParser(usage)

	
	parser.add_option("-m","--maxit",
			action="store", type="int", metavar="N", dest="maxit", default=config.getint("comatsci","maxit"),
			help="Maximum number of NEB iterations for this run, default=%default")

	parser.add_option("-r","--rmstol",
			action="store", type="float", metavar="RMS", dest="rmstol", default=config.getfloat("comatsci","rmstol"),
			help="stop iterating if path rms force in a.u. falls below RMS, default=%default")

	parser.add_option("-f","--forcetol", 
			action="store", type="float", metavar="FMAX", dest="forcetol", default=config.getfloat("comatsci","forcetol"),
			help="stop iterating if path maximum of atomic forces in a.u. falls below FMAX, default=%default")

	parser.add_option("-c","--calculator", 
			action="store", metavar="CALC", dest="calculator", default=config.get("comatsci","calculator"),
			help="use CALC to calculate energies and forces, default=%default")

	parser.add_option("-x","--fixedatoms", 
			action="store", metavar="LIST", dest="fixedatoms", default=config.get("comatsci","fixedatoms"),
			help="Keep atoms in whitespace delimeted LIST fixed, default=%default")
	
	parser.add_option("--charge", 
			action="store", type="float", metavar="Q", dest="charge", default=config.getfloat("comatsci","charge"),
			help="Set Q as the system charge in all path images, default=%default")

	parser.add_option("-v", 
			action="count", dest="verbosity", default=comatsci.constants.VBL_NORMAL,
			help="Increase verbosity level, default=%default")
	
	parser.add_option("-q", "--quiet",
			action="store_const", const=comatsci.constants.VBL_QUIET, dest="verbosity",
			help="Limit output to fatal errors and critical warnings, no status output at all")
			
	parser.add_option("--silence",
			action="store_const", const=comatsci.constants.VBL_SILENCE, dest="verbosity",
			help="Limit output to fatal errors only. Not even warnings.")			

	parser.add_option("-d","--scheduler",
			action="store", type="string", dest="scheduler", default="s",
			help="Choose scheduler to manage execution of single calculations. Choices are 's': serial, 'p': MPI parallel. default=%default")

	parser.add_option("-t","--maxworkthreads",
			action="store", type="int", dest="maxthreads", default=0,
			help="Set maximum number of concurrent parallel threads in thread scheduling mode. 0:= no limit. default=%default")
	
	parser.add_option("--hardtranslation",
			action="store", type="float", dest="hardtranslation", default=config.getfloat("DIMER","hardtranslation"),
			help="Set a fixed trial step width for the translation step. default=%default")
	
	parser.add_option("-a","--rotskipangle",
			action="store", type="float", dest="rotskipangle", default=config.getfloat("DIMER","rotskipangle"),
			help="Set the minimum calculated trial angle for the rotational step. Skip rotation if trial angle is less than ROTSKIPANGLE. 0:= no limit. default=%default")
			
	parser.add_option("--displacement",
			action="store", type="float", dest="displacement", default=config.getfloat("DIMER","displacement"),
			help="The total displacement of R1,R1 with respect to R0, in Angstrom. default=%default")
	
##	parser.add_option("--pathdebug",
##			action="store_true", default=False, dest="pathdebug",
##			help="Store advanced Geometry and forces debug information on path in every iteration")

	# special options for parallel mode go here
	
##	if mode=="p":
       	parser.add_option("-p","",
		action="store", dest="dummy", default=None,
		help="dummy option")


	(options,args) = parser.parse_args()
	

	#special arguments processing for parallel mode goes here
##	if mode=="p":
	# remove some stupid mpich arguments...
	if options.dummy!=None:
		p4wd=args.pop()
		p4pg=args.pop()
	
	#check if at least one mobile image is specified
	if (len(args)<3) and not (len(args)==1 and args[0].endswith(".fmg")):
		print "You must specify at least three structures. Abort."
		return

	#check if valid calculator type was specified
	if not options.calculator in comatsci.constants.PASTACALCS:
		print "Unknown (or unsupported) calculator specified. abort."
		sys.exit(1)
	
	#check if valid scheduler type was specified
	if not options.scheduler in VALIDSCHEDS:
		print "Unknown (or unsupported) scheduler specified. abort."
	
	return (options, config, args)



if __name__ == '__main__':
	# detect MPI environment. If running under MPI, only initialize mpiScheduler as slave
	if os.environ.has_key("LAMRANK"):
		if os.environ["LAMRANK"]=='0':
			mpi=True
			master=True
		else:
			mpi=True
			master=False
	elif os.environ.has_key("MPIRANK"):
		if os.environ["MPIRANK"]=='0':
			mpi=True
			master=True
		else:
			mpi=True
			master=False
	#arminius mpich detection
	elif "-p4amslave" in sys.argv:
		mpi=True
		master=False
	elif "-p4pg" in sys.argv:
		mpi=True
		master=True
	else:
		mpi=False
		master=True
	#master mode
	if master:
		# Store the current path for the signal handlers
		global startpath
		startpath=os.path.realpath(".")
		# Set the signal handlers
		signal.signal(signal.SIGINT, stophandler)
		signal.signal(signal.SIGXCPU, stophandler)
	
		# Parse config file
		dimerrun(mode="s")
	elif mpi:
		mpisched=comatsci.schedulers.mpiScheduler(calcinitializer,None,comatsci.constants.VBL_NORMAL)
